[package]
name = "newhope"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
rand = "0.3"
tiny-keccak = { git = "https://github.com/quininer/tiny-keccak.git" }
byteorder = { version = "0.5", features = [] }
